### ISSUE TITLE
feat: write into storage in `_poolClose` when queuing a tx

### ISSUE THREAD

**Issue by petrovska-petro** [onchainification/robosaver#41]
missing [here](https://github.com/onchainification/robosaver/blob/main/src/RoboSaverVirtualModule.sol#L308) writing into `txQueueData`

**Comment by petrovska-petro** [comment]
explore also this [section](https://github.com/onchainification/robosaver/blob/main/src/RoboSaverVirtualModule.sol#L293-L298)

[sim](https://dashboard.tenderly.co/onchainification/smartgarden-api/tx/gnosis-chain/0x106d9b817005b2c0b1447bab55e04422239724222c6f86322ac070310b46b326)

**Comment by gosuto-inzasheru** [comment]
needs `uint256 public constant EURE_TOKEN_BPT_INDEX_USER = 1;` and to use that in `_poolClose`' `userData`
