### ISSUE TITLE
feat: factory <> enable eoa to delegatecall to automate whole configuration process

### ISSUE THREAD

**Issue by petrovska-petro** [onchainification/robosaver#89]
currently the process require more txs than ideally and process could be ++ abstracted away

leverage factory to automate the flow via delegatecall (r&d if it's even doable!!)

**Comment by gosuto-inzasheru** [comment]
i think this makes #85 obsolete

**Comment by petrovska-petro** [comment]
my conclusions for now, it is that will be doable leveraging the `rolesModule` prob (TBC), do not see currently the way to abstract smoothly via the factory, see #101 test failing: `forge t --mt test_delegationSuccesful -vvv`

**Comment by petrovska-petro** [comment]
after debugging the approach of `delegatecall` we concluded it is not possible as storage layout is mismatching and it returns null for `modules[msg.sender]`. rather UI reliance is a solution here
